[package]
name = "IdGenerator"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = "*"
async-std = { version = "1.6.0", features = ["attributes"] }
futures = "*"
clap = { version = "4.0.26", features = ["derive"] }
